name: herding_cats
version: '1.0.0'
config-version: 2

profile: herding_cats

on-run-start:
  - "INSTALL mssql FROM community;"
  - "LOAD mssql;"
  - "ATTACH 'Server=127.0.0.1,1433;Database={{ env_var('MSSQL_DATABASE') }};User Id={{ env_var('MSSQL_USER') }};Password={{ env_var('MSSQL_PASSWORD') }}' AS sql_server (TYPE MSSQL);"


model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
